export const master = [
  {
    orderNo: "6",
    date: "07-01-2025",
    contact: "Contact 2",
    address: "Contact 2 Address, Coimbatore, Coimbatore, Tamil Nadu - 641004",
    phone: "1234567890",
    remarks: "Demo 2 update",
    createdBy: "Admin",
  },
];
export const details = [
  {
    s_no: "1",
    name: "NEW COOLD",
    style: "RN",
    size: "80",
    qty: "10.00",
  },
  {
    s_no: "2",
    name: "NEW COOLD",
    style: "RN",
    size: "85",
    qty: "10.00",
  },
  {
    s_no: "3",
    name: "NEW COOLD",
    style: "RN",
    size: "90",
    qty: "10.00",
  },
  {
    s_no: "4",
    name: "ROSE PANT",
    style: "3/4TH",
    size: "45",
    qty: "10.00",
  },
  {
    s_no: "5",
    name: "ROSE PANT",
    style: "3/4TH",
    size: "50",
    qty: "10.00",
  },
  {
    s_no: "6",
    name: "ROSE PANT",
    style: "3/4TH",
    size: "55",
    qty: "10.00",
  },
  {
    s_no: "7",
    name: "AJAY - 4 COLLAR",
    style: "RNS",
    size: "50",
    qty: "10.00",
  },
  {
    s_no: "8",
    name: "AJAY - 4 COLLAR",
    style: "RNS",
    size: "55",
    qty: "10.00",
  },
  {
    s_no: "9",
    name: "AJAY - 4 COLLAR",
    style: "RNS",
    size: "60",
    qty: "10.00",
  },
  {
    s_no: "10",
    name: "AJAY - 4 COLLAR",
    style: "RNS",
    size: "65",
    qty: "10.00",
  },
  {
    s_no: "11",
    name: "AJAY - 4 COLLAR",
    style: "RNS",
    size: "70",
    qty: "10.00",
  },
  {
    s_no: "12",
    name: "AJAY - 4 COLLAR",
    style: "RNS",
    size: "75",
    qty: "10.00",
  },
  {
    s_no: "13",
    name: "AJAY - 4 COLLAR",
    style: "RNS",
    size: "80",
    qty: "10.00",
  },
  {
    s_no: "14",
    name: "AJAY - 4 COLLAR",
    style: "RNS",
    size: "85",
    qty: "10.00",
  },
  {
    s_no: "15",
    name: "AJAY - 14 COLLAR",
    style: "RNS",
    size: "50",
    qty: "10.00",
  },
  {
    s_no: "16",
    name: "AJAY - 14 COLLAR",
    style: "RNS",
    size: "55",
    qty: "10.00",
  },
  {
    s_no: "17",
    name: "AJAY - 14 COLLAR",
    style: "RNS",
    size: "60",
    qty: "10.00",
  },
  {
    s_no: "18",
    name: "AJAY - 14 COLLAR",
    style: "RNS",
    size: "65",
    qty: "10.00",
  },
  {
    s_no: "19",
    name: "AJAY - 14 COLLAR",
    style: "RNS",
    size: "70",
    qty: "10.00",
  },
  {
    s_no: "20",
    name: "AJAY - 14 COLLAR",
    style: "RNS",
    size: "75",
    qty: "10.00",
  },
  {
    s_no: "21",
    name: "AJAY - 14 COLLAR",
    style: "RNS",
    size: "80",
    qty: "10.00",
  },
  {
    s_no: "22",
    name: "AJAY - 14 COLLAR",
    style: "RNS",
    size: "85",
    qty: "10.00",
  },
  {
    s_no: "23",
    name: "AJAY - 14 COLLAR",
    style: "RNS",
    size: "90",
    qty: "10.00",
  },
  {
    s_no: "24",
    name: "AKASH-2",
    style: "RNS",
    size: "45",
    qty: "5.00",
  },
  {
    s_no: "25",
    name: "AKASH-2",
    style: "RNS",
    size: "50",
    qty: "5.00",
  },
  {
    s_no: "26",
    name: "AKASH-2",
    style: "RNS",
    size: "55",
    qty: "5.00",
  },
  {
    s_no: "27",
    name: "AKASH-2",
    style: "RNS",
    size: "60",
    qty: "5.00",
  },
  {
    s_no: "28",
    name: "AKASH-2",
    style: "RNS",
    size: "65",
    qty: "5.00",
  },
  {
    s_no: "29",
    name: "AKASH-2",
    style: "RNS",
    size: "70",
    qty: "5.00",
  },
  {
    s_no: "30",
    name: "AKASH-2",
    style: "RNS",
    size: "75",
    qty: "5.00",
  },
  {
    s_no: "31",
    name: "AKASH-2",
    style: "RNS",
    size: "80",
    qty: "5.00",
  },
  {
    s_no: "32",
    name: "LEGGINA ANKEL FIT BUTTER SCOTCH #162",
    style: "FULL",
    size: "85",
    qty: "5.00",
  },
  {
    s_no: "33",
    name: "LEGGINA ANKEL FIT BUTTER SCOTCH #162",
    style: "FULL",
    size: "95",
    qty: "5.00",
  },
  {
    s_no: "34",
    name: "LEGGINA ANKEL FIT BUTTER SCOTCH #162",
    style: "FULL",
    size: "105",
    qty: "5.00",
  },
];
